sudo: required
branches:
  only:
  - master
os:
  - linux

sudo: required

services:
  - docker

language: go

go:
  - 1.11.x
before_install:
- wget https://github.com/mritd/gcrsync/releases/download/v1.3.2/gcrsync_linux_amd64
- sudo mv gcrsync_linux_amd64 gcrsync
- chmod +x gcrsync
- sudo mv gcrsync /usr/local/bin/
script:
#  - gcrsync sync --querylimit 20 --processlimit 10 --httptimeout 10s --user ${DOCKER_USER} --password ${DOCKER_PASSWORD} --githubtoken ${GITHUB_TOKEN} --namespace google-containers --githubrepo chinawyny/gcrsync
 # - gcrsync sync --querylimit 20 --processlimit 10 --httptimeout 10s --user ${DOCKER_USER} --password ${DOCKER_PASSWORD} --githubtoken ${GITHUB_TOKEN} --namespace kubernetes-helm  --githubrepo chinawyny/gcrsync
 # - gcrsync sync --querylimit 20 --processlimit 10 --httptimeout 10s --user ${DOCKER_USER} --password ${DOCKER_PASSWORD} --githubtoken ${GITHUB_TOKEN} --namespace istio-release  --githubrepo chinawyny/gcrsync
 # - gcrsync sync --querylimit 20 --processlimit 10 --httptimeout 10s --user ${DOCKER_USER} --password ${DOCKER_PASSWORD} --githubtoken ${GITHUB_TOKEN} --namespace linkerd-io  --githubrepo chinawyny/gcrsync
 # - gcrsync sync --querylimit 20 --processlimit 10 --httptimeout 10s --user ${DOCKER_USER} --password ${DOCKER_PASSWORD} --githubtoken ${GITHUB_TOKEN} --namespace spinnaker-marketplace  --githubrepo chinawyny/gcrsync
  - gcrsync sync --querylimit 20 --processlimit 10 --httptimeout 10s --user ${DOCKER_USER} --password ${DOCKER_PASSWORD} --githubtoken ${GITHUB_TOKEN} --namespace distroless  --githubrepo chinawyny/change_log
